[package]
name = "zsp-fs"
version = "0.1.0"
edition = "2021"
workspace = "../../"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zsp-core = {path = "../../core"}

[lib]
crate-type = ["cdylib"]