[package]
name = "zsp-std"
version = "0.1.0"
edition = "2021"
workspace = "../"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zsp-interpreter = {path = "../interpreter"}
serde = "*"
serde_json = "*"

[lib]
crate-type = ["cdylib"]